// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/openshift/assisted-service/models"
)

// NewRegisterPoolClusterParams creates a new RegisterPoolClusterParams object
// no default values defined in spec.
func NewRegisterPoolClusterParams() RegisterPoolClusterParams {

	return RegisterPoolClusterParams{}
}

// RegisterPoolClusterParams contains all the bound params for the register pool cluster operation
// typically these are obtained from a http.Request
//
// swagger:parameters RegisterPoolCluster
type RegisterPoolClusterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Parameters for creating a new pool cluster.
	  Required: true
	  In: body
	*/
	NewPoolClusterParams *models.PoolClusterCreateParams
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRegisterPoolClusterParams() beforehand.
func (o *RegisterPoolClusterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.PoolClusterCreateParams
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("newPoolClusterParams", "body", ""))
			} else {
				res = append(res, errors.NewParseError("newPoolClusterParams", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewPoolClusterParams = &body
			}
		}
	} else {
		res = append(res, errors.Required("newPoolClusterParams", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
