// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RegisterPoolClusterHandlerFunc turns a function with the right signature into a register pool cluster handler
type RegisterPoolClusterHandlerFunc func(RegisterPoolClusterParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterPoolClusterHandlerFunc) Handle(params RegisterPoolClusterParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// RegisterPoolClusterHandler interface for that can handle valid register pool cluster params
type RegisterPoolClusterHandler interface {
	Handle(RegisterPoolClusterParams, interface{}) middleware.Responder
}

// NewRegisterPoolCluster creates a new http.Handler for the register pool cluster operation
func NewRegisterPoolCluster(ctx *middleware.Context, handler RegisterPoolClusterHandler) *RegisterPoolCluster {
	return &RegisterPoolCluster{Context: ctx, Handler: handler}
}

/*RegisterPoolCluster swagger:route POST /pool_clusters installer registerPoolCluster

Create a new pool cluster definition, used for holding nodes that will later be moved to day1/day2 clusters

*/
type RegisterPoolCluster struct {
	Context *middleware.Context
	Handler RegisterPoolClusterHandler
}

func (o *RegisterPoolCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterPoolClusterParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
