// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// NewRegisterPoolClusterParams creates a new RegisterPoolClusterParams object
// with the default values initialized.
func NewRegisterPoolClusterParams() *RegisterPoolClusterParams {
	var ()
	return &RegisterPoolClusterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRegisterPoolClusterParamsWithTimeout creates a new RegisterPoolClusterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRegisterPoolClusterParamsWithTimeout(timeout time.Duration) *RegisterPoolClusterParams {
	var ()
	return &RegisterPoolClusterParams{

		timeout: timeout,
	}
}

// NewRegisterPoolClusterParamsWithContext creates a new RegisterPoolClusterParams object
// with the default values initialized, and the ability to set a context for a request
func NewRegisterPoolClusterParamsWithContext(ctx context.Context) *RegisterPoolClusterParams {
	var ()
	return &RegisterPoolClusterParams{

		Context: ctx,
	}
}

// NewRegisterPoolClusterParamsWithHTTPClient creates a new RegisterPoolClusterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRegisterPoolClusterParamsWithHTTPClient(client *http.Client) *RegisterPoolClusterParams {
	var ()
	return &RegisterPoolClusterParams{
		HTTPClient: client,
	}
}

/*RegisterPoolClusterParams contains all the parameters to send to the API endpoint
for the register pool cluster operation typically these are written to a http.Request
*/
type RegisterPoolClusterParams struct {

	/*NewPoolClusterParams
	  Parameters for creating a new pool cluster.

	*/
	NewPoolClusterParams *models.PoolClusterCreateParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the register pool cluster params
func (o *RegisterPoolClusterParams) WithTimeout(timeout time.Duration) *RegisterPoolClusterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the register pool cluster params
func (o *RegisterPoolClusterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the register pool cluster params
func (o *RegisterPoolClusterParams) WithContext(ctx context.Context) *RegisterPoolClusterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the register pool cluster params
func (o *RegisterPoolClusterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the register pool cluster params
func (o *RegisterPoolClusterParams) WithHTTPClient(client *http.Client) *RegisterPoolClusterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the register pool cluster params
func (o *RegisterPoolClusterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNewPoolClusterParams adds the newPoolClusterParams to the register pool cluster params
func (o *RegisterPoolClusterParams) WithNewPoolClusterParams(newPoolClusterParams *models.PoolClusterCreateParams) *RegisterPoolClusterParams {
	o.SetNewPoolClusterParams(newPoolClusterParams)
	return o
}

// SetNewPoolClusterParams adds the newPoolClusterParams to the register pool cluster params
func (o *RegisterPoolClusterParams) SetNewPoolClusterParams(newPoolClusterParams *models.PoolClusterCreateParams) {
	o.NewPoolClusterParams = newPoolClusterParams
}

// WriteToRequest writes these params to a swagger request
func (o *RegisterPoolClusterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.NewPoolClusterParams != nil {
		if err := r.SetBodyParam(o.NewPoolClusterParams); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
